version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET:-change-me-in-production}
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
